# Change these first
owner: 1MaddieX # Your GitHub username
repo: conan-status # Your Github repository name

# Add your sites here
sites:
  - name: Homepage
    url: https://conan-ai.co
  - name: Medousa (Authentication)
    url: https://auth.conan-ai.co:32168/
  - name: Rosetta (NLU)
    url: https://nlu.conan-ai.co:32168/
  - name: Einstein (API)
    url: https://api.conan-ai.co:32168/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.conan-ai.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Conan Status
  introTitle: "Welcome to the Conan AI status page!"
  introMessage: "You're probably here because we f*&cked up and the app isn't working, or you're just really curious, or bored, either way welcome!"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
